language: node_js
node_js:
- node
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
env:
  global:
    secure: GmZXS6Wyzl+NbALvbbJZC9suuZi4U15nq5SMyL1fVDE5NagHWwh6FpTcJ0iW21gP+sMwdxm6HeYGjq2DcN9udPHVl2ddRYj3tBsBlZm9OfTwpT6dS7tlu88w5d29wR9y7ViVzmoTmQgFdhy5nWp8mQS0PLvfJmqE0oTGx4uGAN0AY9/ePQHoTWke/aWUDlBBFTZASE0369/nuTFUvrimbUFT0HO4mfvHSgkR37u5xSiYNO+C16eMR1ImBOUwC7qmQDrOeZz67AzSyJH7mG+xmwFZW9/E6t+YPUynB/Nq3XtJ46FKDHGtzdSffbuzOXY5gy57DHWygAViI2ebz/mbJbhhmEcoMLSy0vTvCcHyw6uQR4A7eCvefvvqwlTLb6PYjDrKHSnLvKnZ1Xs6me0SAOvLVoQh79PMwKL2urDl+y8olnKrwKmc3a0B+rtn3wrGZdEdEhqqgbhcgCss/hi+lr1OLHLpZCQYanhwN+zsBTiXZumUQpBIcw5Txxg/aRrnf9bUVuBZOxWnCTsDzJBZELUlg50/u5QNbnVZVzojpdG3zYAZjxx4fejvHx98YFJ7eGzIV2KRQpEAd+7RaMYPxoZqSoZpXJMmXJv337U5XUpkho8BQehEAOgyE7zZrAhwWXF1ug7yDBG2CxqmZ52r4EjqYoWqtp0wU/W7qcpGgxI=
