language: node_js
node_js:
- node
install:
- npm install
script:
- npm run build
- npm test
deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
env:
  global:
    secure: WZtA16V40DGCrQyov5P6XRmtqLaR+52x2ibD+3p7JBXmT+OMH39TDw1SZU4b/O8kPxbxll23TXqc7KnluhbBdaCwUQxAPmTAyaDH039p+L8jSemQQ7UfdMqMr4iP9dHqgAlxpy6R7pbMDlrMmsCvxsva1L9Q1UPFHvhPwhTqj/DdpQM19cMlyXKRQw3IYE9z3IBiP0guZS5vN3TYQXXGc5pb/TJSWLo7VU118hcN3JPquS9pnj0A2L4A986da/MUMkH+b3foxgUMlEAQFdFv75W7sBqJGi09v9xoLKoejdL6DPB5FyA+VxZWfTAwVL8polS2fkgAnAFnqhjehsedrB6fQfS4GpnPFjLpJVJ/kEL9rAmwGyTZ39Qwoknt8Zruz7OIiIWPGYWwl5BZT88ewgNTT8p3vHF4N87nW/jOLVJuYo9ztUF1YqyjCqz3a58chEF+vEzv4ICUeFwaxZ8ecjpMdINvNYjh564gFo04PE3rDIK+8nEhugKBA+vYAi9+L40y2uSW6DaMNQFmGfGL6UxUoHGFvy3emNTosTRrw6sFJj8bppafYsbXrxdFFlmwuVEekdetLvSV03QNDYAxk1+Ychra63nlpjBS3fKIzSVN8De94gwZ6y3BkPuWATkcOplosGE15u6/MN4UqTRG6FQ4ZxRllDQTl5Dm+bvqwAU=
