language: node_js
node_js:
  - "node"

install:
  - npm install

script:
  - npm run build
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script: npm run deploy
  on:
    branch: master
